v0.46
update pkgx deps

diff --git a/bin/pkg b/bin/pkg
--- a/bin/pkg
+++ b/bin/pkg
@@ -1,4 +1,4 @@
-#!/usr/bin/env -S tea bash
+#!/usr/bin/env -S pkgx bash
 # shellcheck shell=bash
 
 set -e
@@ -16,17 +16,17 @@ shift
 
 if test "$arg" = "-v" || test "$arg" = "--version"; then
   d="$(cd "$(dirname "$0")"/.. && pwd)"
-  if echo "$d" | grep -q "$(tea --prefix)/tea.xyz/brewkit"; then
-    V="${d#"$(tea --prefix)"/tea.xyz/brewkit/}"
+  if echo "$d" | grep -q "${PKGX_DIR:-$HOME/.pkgx}/tea.xyz/brewkit"; then
+    V="${d#"${PKGX_DIR:-$HOME/.pkgx}"/tea.xyz/brewkit/}"
   else
     V="$(git describe --tags --abbrev=0 --match "v[0-9]*.[0-9]*.[0-9]*")-dev"
   fi
-  echo "tea.xyz/brewkit: $V"
+  echo "brewkit: $V"
   exit 0
 fi
 
 if test "$arg" = "-L"; then
-  export TEA_DOCKER=1
+  export PKGX_DOCKER=1
 
   if test -n "$1"; then
     arg="$1"
@@ -42,6 +42,6 @@ if test -x "$d"/pkg-"$arg"; then
 elif test "$(find "$d" -name "pkg-$arg*" | wc -l)" -eq 1; then
   exec "$d"/pkg-"$arg"* "$@"
 else
-  echo "tea.xyz/brewkit: error: unknown or ambiguous command '$arg'" >&2
+  echo "brewkit: error: unknown or ambiguous command '$arg'" >&2
   exit 1
 fi
diff --git a/bin/pkg-build b/bin/pkg-build
--- a/bin/pkg-build
+++ b/bin/pkg-build
@@ -1,10 +1,12 @@
-#!/usr/bin/env -S tea bash
+#!/usr/bin/env -S pkgx bash
 # shellcheck shell=bash
 
 set -e
 
+PKGX_DIR=${PKGX_DIR:-"$HOME/.pkgx"}
+
 if pwd | grep -q ' '; then
-  echo "tea.xyz/brewkit: warning: current directory contains spaces. builds *will* break!" >&2
+  echo "brewkit: warning: current directory contains spaces. builds *will* break!" >&2
 fi
 
 if test -n "$RUNNER_DEBUG" -a -n "$GITHUB_ACTIONS" -o -n "$VERBOSE"; then
@@ -15,11 +17,11 @@ d="$(cd "$(dirname "$0")"/.. && pwd)"
 PATH="$d/libexec:$PATH"
 
 if test -z "$1"; then
-  if test -z "$TEA_PANTRY_PATH"; then
-    echo "error: TEA_PANTRY_PATH is not set" >&2
+  if test -z "$PKGX_PANTRY_PATH"; then
+    echo "error: PKGX_PANTRY_PATH is not set" >&2
     exit 1
   fi
-  for x in $(echo "$TEA_PANTRY_PATH" | tr ':' '\n'); do
+  for x in $(echo "$PKGX_PANTRY_PATH" | tr ':' '\n'); do
     if test -d "$x"/.git; then
       PKGS="$(GIT_WORK_TREE="$x" peek.sh) $PKGS"
     fi
@@ -28,7 +30,7 @@ else
   PKGS="$*"
 fi
 
-if test -n "$TEA_DOCKER"; then
+if test -n "$PKGX_DOCKER"; then
   exec "$d"/bin/pkg-docker build "$PKGS"
 fi
 
@@ -38,7 +40,7 @@ if ! available.ts "$@"; then
 fi
 
 if test -z "$GITHUB_TOKEN"; then
-  GITHUB_TOKEN=$(tea gh auth token)
+  GITHUB_TOKEN=$(pkgx gh auth token)
   if test -z "$GITHUB_TOKEN"; then
     echo "error: builds need a GITHUB_TOKEN. Either export that or run \`gh auth login\`" >&2
     exit 1
@@ -51,7 +53,7 @@ PKGS="$(sort.ts $PKGS --delimiter ' ')"
 # ^^ ensures that pkgs build topologically
 
 gum() {
-  tea gum format -- "$@"
+  pkgx gum format -- "$@"
 }
 
 for PKG in $PKGS; do
@@ -80,7 +82,7 @@ for PKG in $PKGS; do
   DEPS=$(deps.ts "$PKG" --build)  # eg. nodejs.org^4
 
   # shellcheck disable=SC2086
-  DEPS=$(install.ts $DEPS)      # eg. ~/.tea/nodejs.org/v4.3.2
+  DEPS=$(install.ts $DEPS)      # eg. ~/.pkgx/nodejs.org/v4.3.2
 
   mkdir -p "$SRCDIR"
   BUILD_SCRIPT="$(stage.ts "$PKG" --srcdir "$SRCDIR" --prefix "$PREFIX" --deps "$DEPS" --build-dir "$BLDDIR")"
@@ -88,8 +90,10 @@ for PKG in $PKGS; do
   if command -v bash >/dev/null; then
     BASH=bash
   else
-    BASH="tea bash"
+    BASH="pkgx bash"
   fi
+
+  echo "build-dir=$BLDDIR" >> $GITHUB_OUTPUT
 
   gum "# running build"
 
@@ -116,11 +120,11 @@ for PKG in $PKGS; do
 
   if test -n "$GITHUB_ACTIONS"; then
     GH_PKGS="$GH_PKGS $PKG"
-    GH_RELATIVE_PATHS="$GH_RELATIVE_PATHS ${PREFIX#"$TEA_PREFIX"/}"
+    GH_RELATIVE_PATHS="$GH_RELATIVE_PATHS ${PREFIX#"$PKGX_DIR"/}"
 
     if test -f "$ZIP"; then
-      GH_SRCS="$GH_SRCS ${ZIP#"$TEA_PREFIX"/}"
-      GH_SRCS_RELATIVE_PATHS="$GH_SRCS_RELATIVE_PATHS ${ZIP#"$TEA_PREFIX"/}"
+      GH_SRCS="$GH_SRCS ${ZIP#"$PKGX_DIR"/}"
+      GH_SRCS_RELATIVE_PATHS="$GH_SRCS_RELATIVE_PATHS ${ZIP#"$PKGX_DIR"/}"
     else
       GH_SRCS="$GH_SRCS ~"
     fi
diff --git a/bin/pkg-clean b/bin/pkg-clean
--- a/bin/pkg-clean
+++ b/bin/pkg-clean
@@ -1,4 +1,4 @@
-#!/usr/bin/env -S tea bash
+#!/usr/bin/env -S pkgx bash
 # shellcheck shell=bash
 
 set -e
@@ -7,11 +7,11 @@ d="$(cd "$(dirname "$0")"/.. && pwd)"
 PATH="$d/libexec:$PATH"
 
 if test -z "$1"; then
-  if test -z "$TEA_PANTRY_PATH"; then
-    echo "error: TEA_PANTRY_PATH is not set" >&2
+  if test -z "$PKGX_PANTRY_PATH"; then
+    echo "error: PKGX_PANTRY_PATH is not set" >&2
     exit 1
   fi
-  for x in $(echo "$TEA_PANTRY_PATH" | tr ':' '\n'); do
+  for x in $(echo "$PKGX_PANTRY_PATH" | tr ':' '\n'); do
     if test -d "$x"/.git; then
       PKGS="$(GIT_WORK_TREE="$x" peek.sh) $PKGS"
     fi
@@ -21,7 +21,7 @@ else
 fi
 
 if test -z "$GITHUB_TOKEN"; then
-  GITHUB_TOKEN=$(tea gh auth token)
+  GITHUB_TOKEN=$(pkgx gh auth token)
   export GITHUB_TOKEN
 fi
 
diff --git a/bin/pkg-docker b/bin/pkg-docker
--- a/bin/pkg-docker
+++ b/bin/pkg-docker
@@ -1,4 +1,4 @@
-#!/usr/bin/env -S tea bash
+#!/usr/bin/env -S pkgx bash
 # shellcheck shell=bash
 
 set -e
@@ -7,21 +7,18 @@ d="$(cd "$(dirname "$0")/.." && pwd)"
 
 arg0="$1"
 
-if test -z "$TEA_PREFIX"; then
-  echo "tea.xyz/brewkit: error: TEA_PREFIX unset" >&2
-  exit 1
-fi
+PKGX_DIR="${PKGX_DIR:-$HOME/.pkgx}"
 
 if test -z "$GITHUB_TOKEN"; then
-  GITHUB_TOKEN=$(tea gh auth token)
+  GITHUB_TOKEN=$(pkgx gh auth token)
 fi
 
 if test "$arg0" = docker; then
-  echo "tea.xyz/brewkit: error: invalid usage" >&2
+  echo "brewkit: error: invalid usage" >&2
   exit 1
 elif shift; then
   # ensure this brewkit is used
-  CMD="tea +deno.land ""$d/bin/pkg-$arg0"
+  CMD="pkgx +deno.land ""$d/bin/pkg-$arg0"
   ADDARGS="--volume ""$d"":""$d"
 else
   # we were invoked as `pkg -L` by itself
@@ -29,48 +26,46 @@ else
 fi
 
 STDARGS="
-  --name brewkit.tea.xyz
+  --name brewkit.pkgx.dev
   --rm
   --tty
   --env GITHUB_TOKEN=$GITHUB_TOKEN
   --env CLICOLOR_FORCE=1
   "
 
-if test "$TEA_PANTRY_PATH" = "$SRCROOT"; then
+if test "$PKGX_PANTRY_PATH" = "$SRCROOT"; then
   # we’re running in a pantry checkout
 
-  mkdir -p "$TEA_PANTRY_PATH/prefixes/linux"
+  mkdir -p "$PKGX_PANTRY_PATH/prefixes/linux"
 
-  tea gum format "# docker pull"
+  pkgx gum format "# docker pull"
 
-  docker image pull teaxyz/cli
+  docker image pull pkgxdev/pkgx
 
-  tea gum format "# docker run"
+  pkgx gum format "# docker run"
 
   docker run \
     $STDARGS \
     $ADDARGS \
-    --volume "$TEA_PANTRY_PATH":/work \
+    --volume "$PKGX_PANTRY_PATH":/work \
     --env SRCROOT=/work \
     --volume /root/pantry/prefixes \
-    --volume "$TEA_PANTRY_PATH"/prefixes/linux:/root/.tea \
-    --volume "$TEA_PREFIX/tea.xyz/var/www":/root/.tea/tea.xyz/var/www \
-    --volume "$TEA_PANTRY_PATH"/projects:/root/.tea/tea.xyz/var/pantry/projects \
-    --env DENO_DIR=/root/.tea/.local/.cache/deno \
-    teaxyz/cli \
+    --volume "$PKGX_PANTRY_PATH"/prefixes/linux:/root/.pkgx \
+    --volume "$PKGX_PANTRY_PATH"/projects:/root/.local/share/pkgx/pantry/projects \
+    --env DENO_DIR=/root/.pkgx/.cache/deno \
+    pkgxdev/pkgx \
     $CMD "$@"
 else
-  if test -n "$TEA_PANTRY_PATH"; then
-    ADDARGS="--volume ""$TEA_PANTRY_PATH"":/root/.tea/tea.xyz/var/pantry ""$ADDARGS"
+  if test -n "$PKGX_PANTRY_PATH"; then
+    ADDARGS="--volume ""$PKGX_PANTRY_PATH"":/root/.local/share/pkgx/pantry ""$ADDARGS"
   fi
 
-  docker image pull teaxyz/cli
+  docker image pull pkgxdev/pkgx
 
   docker run \
     $STDARGS \
-    --volume "$TEA_PREFIX/tea.xyz/var":/root/.tea/tea.xyz/var \
     $ADDARGS \
-    teaxyz/cli \
+    pkgxdev/pkgx \
     $CMD "$@"
 fi
 
diff --git a/bin/pkg-edit b/bin/pkg-edit
--- a/bin/pkg-edit
+++ b/bin/pkg-edit
@@ -1,4 +1,4 @@
-#!/usr/bin/env -S tea bash
+#!/usr/bin/env -S pkgx bash
 # shellcheck shell=bash
 
 set -e
@@ -7,18 +7,18 @@ d="$(cd "$(dirname "$0")"/.. && pwd)"
 PATH="$d/libexec:$PATH"
 
 if test -z "$1"; then
-  if test -z "$TEA_PANTRY_PATH"; then
-    echo "error: TEA_PANTRY_PATH is not set" >&2
+  if test -z "$PKGX_PANTRY_PATH"; then
+    echo "error: PKGX_PANTRY_PATH is not set" >&2
     exit 1
   fi
-  for x in $(echo "$TEA_PANTRY_PATH" | tr ':' '\n'); do
+  for x in $(echo "$PKGX_PANTRY_PATH" | tr ':' '\n'); do
     if test -z "$PKGS" -a -d "$x"/.git; then
       #^^^^^^^^^^^^^^^ stop at first match
       PKGS="$(GIT_WORK_TREE="$x" peek.sh --print-paths)"
     fi
   done
 elif ! PKGS="$(find.ts $1)"; then
-  echo "error: \`$1\` not found in \`\$TEA_PANTRY_PATH\`" >&2
+  echo "error: \`$1\` not found in \`\$PKGX_PANTRY_PATH\`" >&2
   exit 1
 fi
 
@@ -42,11 +42,11 @@ elif test "$EDITOR" = code_wait; then
 fi
 
 if test -z "$PKGS"; then
-  echo "error: no new packages in \`\$TEA_PANTRY_PATH\`" >&2
+  echo "error: no new packages in \`\$PKGX_PANTRY_PATH\`" >&2
   exit 1
 elif test "$EDITOR" = code; then
   # shellcheck disable=2086
-  exec $EDITOR $TEA_PANTRY_PATH $PKGS
+  exec $EDITOR $PKGX_PANTRY_PATH $PKGS
   # ^^ be more useful
 else
   # shellcheck disable=2086
diff --git a/bin/pkg-init b/bin/pkg-init
--- a/bin/pkg-init
+++ b/bin/pkg-init
@@ -1,23 +1,18 @@
-#!/usr/bin/env -S tea bash
+#!/usr/bin/env -S pkgx bash>=4
 # shellcheck shell=bash
-
-# --
-# dependencies:
-#   - gnu.org/bash: '>=4'
-# --
 
 set -eo pipefail
 
-if test -z "$TEA_PANTRY_PATH"; then
-  echo "error: TEA_PANTRY_PATH is not set" >&2
+if test -z "$PKGX_PANTRY_PATH"; then
+  echo "error: PKGX_PANTRY_PATH is not set" >&2
   exit 1
 fi
 
-WHERE="$(echo "$TEA_PANTRY_PATH" | cut -d: -f1)"
+WHERE="$(echo "$PKGX_PANTRY_PATH" | cut -d: -f1)"
 GIT_DIR="$WHERE/.git"
 
 if ! test -d "$GIT_DIR"; then
-  echo "error: TEA_PANTRY_PATH is not a standard git repository" >&2
+  echo "error: PKGX_PANTRY_PATH is not a standard git repository" >&2
   exit 1
 fi
 
@@ -30,7 +25,7 @@ d="$(cd "$(dirname "$0")"/.. && pwd)"
 PATH="$d/libexec:$PATH"
 
 if ! command -v ruby >/dev/null; then
-  RUBY="tea +ruby-lang.org"
+  RUBY="pkgx +ruby"
 fi
 
 BLEND="$($RUBY init.ts "$1")"
@@ -48,7 +43,7 @@ if test "$(git rev-parse --abbrev-ref HEAD)" != "new/$BLEND"; then
   git checkout -b "new/$BLEND" origin/main
 fi
 
-tea gum format <<EOF
+pkgx gum format <<EOF
 # created \`$PRETTY\`
 
 Now type \`pkg edit\` to open the yaml in your \`\$EDITOR\`
diff --git a/bin/pkg-test b/bin/pkg-test
--- a/bin/pkg-test
+++ b/bin/pkg-test
@@ -1,4 +1,4 @@
-#!/usr/bin/env -S tea bash
+#!/usr/bin/env -S pkgx bash
 # shellcheck shell=bash
 
 set -e
@@ -7,11 +7,11 @@ d="$(cd "$(dirname "$0")"/.. && pwd)"
 PATH="$d/libexec:$PATH"
 
 if test -z "$1"; then
-  if test -z "$TEA_PANTRY_PATH"; then
-    echo "error: TEA_PANTRY_PATH is not set" >&2
+  if test -z "$PKGX_PANTRY_PATH"; then
+    echo "error: PKGX_PANTRY_PATH is not set" >&2
     exit 1
   fi
-  for x in $(echo "$TEA_PANTRY_PATH" | tr ':' '\n'); do
+  for x in $(echo "$PKGX_PANTRY_PATH" | tr ':' '\n'); do
     if test -d "$x"/.git; then
       PKGS="$(GIT_WORK_TREE="$x" peek.sh) $PKGS"
     fi
@@ -20,7 +20,7 @@ else
   PKGS="$*"
 fi
 
-if test -n "$TEA_DOCKER"; then
+if test -n "$PKGX_DOCKER"; then
   exec "$d"/bin/pkg-docker test "$PKGS"
 fi
 
@@ -30,7 +30,7 @@ if ! available.ts "$@"; then
 fi
 
 gum() {
-  tea gum format -- "$@"
+  pkgx gum format -- "$@"
 }
 
 for PKG in $PKGS; do
@@ -57,12 +57,12 @@ for PKG in $PKGS; do
   if command -v bash >/dev/null; then
     BASH=bash
   else
-    BASH="tea bash"
+    BASH="pkgx bash"
   fi
 
   gum "## running test"
 
-  env -i "$BASH" --noprofile --norc -e "$DSTDIR"/xyz.tea.test.sh
+  env -i "$BASH" --noprofile --norc -e "$DSTDIR"/dev.pkgx.test.sh
 
   gum "## running audit"
 
