short command names

diff --git a/bin/pkg b/bin/pkg
--- a/bin/pkg
+++ b/bin/pkg
@@ -29,7 +29,14 @@ fi
 
 if test -n "$arg"; then
   d="$(cd "$(dirname "$0")" && pwd)"
-  exec "$d"/pkg-"$arg" "$@"
+  if test -x "$d"/pkg-"$arg"; then
+    exec "$d"/pkg-"$arg" "$@"
+  elif test "$(find "$d" -name "pkg-$arg*" | wc -l)" -eq 1; then
+    exec "$d"/pkg-"$arg"* "$@"
+  else
+    echo "tea.xyz/brewkit: error: unknown or ambiguous command '$arg'" >&2
+    exit 1
+  fi
 else
   echo "tea.xyz/brewkit: error: invalid usage" >&2
   exit 1
